config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :stickers
  devise_for :users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  # root 'landing#index'
  get '/tesla' => 'home#index'
  resources :feedback, only: :create

  root 'main#index'
  get 'index'  => 'main#index'
  get 'all'    => 'main#all'
  get '/today' => 'main#today'

  get 'download/file' # all types
  # resources :feedback, only: :create

  # match '/council',         :to => 'contents/synod#index',           via: :get, as: :council
  # match '/administrations', :to => 'contents/administrations#index', via: :get, as: :administration

  # namespace :contents, path: "", as: "" do
  # image, tag, attacheable_id, attacheable_type
  # has_many gallery

  # resources :subscription

  # resources :images

  get 'to_day/index', controller: 'contents/to_day'
  get 'to_day/show',  controller: 'contents/to_day'

  resources :users, only: %i[index show],                              controller: 'contents/users'
  resources :attachments,                                              controller: 'contents/attachments'

  resources :navigator,                                                controller: 'contents/navigators'
  resources :navigator_items,                                          controller: 'contents/navigator_items'
  resources :menu_items,                                               controller: 'contents/menu_items'
  resources :messages,                                                 controller: 'contents/messages' # , only: [:new, :create, :show, :edit, :update]                  #+

  get '/news',                          to: 'contents/news#index',     controller: 'contents/news', as: :news_index
  get '/news/one/:id',                  to: 'contents/news#show',      controller: 'contents/news', as: :news

  resources :authorities,               only: %i[index show],          controller: 'contents/authorities'
  resources :synods,                    only: :index, path: 'council', controller: 'contents/synods'
  resources :administrations,           only: :index,                  controller: 'contents/administrations'
  resources :documents,                 only: :index,                  controller: 'contents/documents'

  resources :galleries,                 only: %i[index show],          controller: 'contents/galleries'
  resources :posters,                   only: %i[index show],          controller: 'contents/posters'

  resources :abouts,                    only: :index,                  controller: 'contents/abouts'                                    # menu item
  resources :symbologies,               only: :index,                  controller: 'contents/symbologies'
  resources :histories,                 only: :index,                  controller: 'contents/histories'

  resources :officials,                 only: :index,                  controller: 'contents/officials'                                 #-
  resources :inspections,               only: :index,                  controller: 'contents/inspections'
  resources :inspection_ratings,        only: :index,                  controller: 'contents/inspection_ratings'
  resources :statistics,                only: :index,                  controller: 'contents/statistics'
  resources :external_contacts,         only: :index,                  controller: 'contents/external_contacts', path: 'ec/внешние связи города'
  resources :external_contact_contents, only: %i[index show],          controller: 'contents/external_contacts', path: 'ec/внешние связи города/контент'
  resources :anticorrupts,              only: %i[index show],          controller: 'contents/anticorrupts'
  resources :people,                    only: %i[index show],          controller: 'contents/people'
  resources :vacancies,                 only: %i[index show],          controller: 'contents/vacancies'

  resources :for_guests,                only: :index,                  controller: 'contents/for_guests' # link to :messages, :navigators
  resources :for_settlers,              only: :index,                  controller: 'contents/for_settlers' # link to :messages, :navigators

  get '/404', to: 'errors#error_404'
  get '/422', to: 'errors#error_422'
  get '/500', to: 'errors#error_500'
  get '/505', to: 'errors#error_505'

  match '/404' => 'errors#error_404', via: %i[get post patch delete]

  # You can have the root of your site routed with "root"

  # Верстка
  resources :mockups do
    get :index,
        :news,
        :news_one,
        :history,
        :symbols,
        :gallery,
        :gallery_one,
        :official,
        :message,
        :docs,
        :people,
        :afisha,
        :navigator,
        :gov,
        :text_page,
        on: :collection
  end

  # Example of regular route:
  #   get 'products/:id' => 'catalog#view'

  # Example of named route that can be invoked with purchase_url(id: product.id)
  #   get 'products/:id/purchase' => 'catalog#purchase', as: :purchase

  # Example resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Example resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end

  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end
end

app/models/external_contact.rb
# frozen_string_literal: true

class ExternalContact < ActiveRecord::Base
  has_many :attachments, as: :attacheable, dependent: :destroy
  has_many :external_contact_contents, dependent: :destroy
  accepts_nested_attributes_for :attachments
  has_ancestry
end

# == Schema Information
#
# Table name: external_contacts
#
#  ancestry   :string(255)
#  created_at :datetime         not null
#  id         :integer          not null, primary key
#  name       :string(255)
#  parent_id  :integer
#  text       :string(255)
#  title      :string(255)
#  updated_at :datetime         not null
#
# Indexes
#
#  index_external_contacts_on_ancestry  (ancestry)
#

app/controllers/contents/external_contacts_controller.rb
# frozen_string_literal: true

class Contents::ExternalContactsController < ApplicationController
  before_action :set_external_contact, only: %i[show edit update destroy]

  # GET /external_contacts
  # GET /external_contacts.json
  def index
    # @external_contacts = ExternalContact.all
    @external_contacts = ExternalContact.where("title = 'внешние связи города' OR title = 'main one'").first
  end

  # GET /external_contacts/1
  # GET /external_contacts/1.json
  def show; end

  # GET /external_contacts/new
  def new
    # @external_contact = ExternalContact.new

    @external_contact = ExternalContact.new(parent_id: params[:parent_id])
  end

  # GET /external_contacts/1/edit
  def edit; end

  # POST /external_contacts
  # POST /external_contacts.json
  def create
    @external_contact = ExternalContact.new(external_contact_params)

    respond_to do |format|
      if @external_contact.save
        format.html { redirect_to @external_contact, notice: 'External contact was successfully created.' }
        format.json { render :show, status: :created, location: @external_contact }
      else
        format.html { render :new }
        format.json { render json: @external_contact.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /external_contacts/1
  # PATCH/PUT /external_contacts/1.json
  def update
    respond_to do |format|
      if @external_contact.update(external_contact_params)
        format.html { redirect_to @external_contact, notice: 'External contact was successfully updated.' }
        format.json { render :show, status: :ok, location: @external_contact }
      else
        format.html { render :edit }
        format.json { render json: @external_contact.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /external_contacts/1
  # DELETE /external_contacts/1.json
  def destroy
    @external_contact.destroy
    respond_to do |format|
      format.html { redirect_to external_contacts_url, notice: 'External contact was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_external_contact
    @external_contact = ExternalContact.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def external_contact_params
    params.require(:external_contact).permit(:parent_id, :title, :text, :attacheable_type, attachments_attributes: [:attach])
    # params.require(:external_contact).permit(:name, :text)
  end
end

app/helpers/external_contacts_helper.rb
# frozen_string_literal: true

module ExternalContactsHelper
  def nested_sub(mainmenus)
    mainmenus.map do |mm, sm|
      render partial: 'admin/external_contacts/sub_item', locals: { mm: mm, sm: sm }
    end.join.html_safe
  end
  #
  #   def nested_sub(mainmenus)
  #     mainmenus.map do |mm, sm|
  #       @childs = Mainmenu.where(:mid => mm.id, :menutype => "child")
  #
  #       if mm.menutype != "link"
  #         @cls = "dropdown" if mm.menutype == "main"
  #         @cls = "dropdown-submenu" if mm.menutype != "main"
  #         @cls = "dropdown with-childmenu" if mm.menutype == "main" && (@childs.size > 0 || sm.size > 0)
  #       else
  #         @cls = "link" if mm.menutype == "link"
  #       end
  #
  #       render partial: "mainmenus/topmenu/menu.haml", locals: {:mm => mm, :sm => sm}
  #     end.join.html_safe
  #   end
  #
  #   def admin_nested_mainmenus(mm)
  #     render "mainmenus/admin/menu", :mainmenus => mm
  #   end
end

app/views/admin/external_contacts/_attach_functions.slim
= link_to "открыть", admin_attachment_path(attache)
/'  |
/= link_to "редактировать", edit_admin_attachment_path(attache)
'  |
= link_to "удалить", admin_attachment_path(attache), method: :delete, remote: true

app/views/admin/external_contacts/_form.slim
= form_for [:admin, @external_contact], :html => { :enctype => "multipart/form-data" } do |f|
  - if @external_contact.errors.any?
    #error_explanation
      h2 = "#{pluralize(@external_contact.errors.count, "error")} prohibited this document from being saved:"
      ul
        - @external_contact.errors.full_messages.each do |message|
          li = message

  /= f.hidden_field :ancestry, velue: @external_contact.ancestry
  = f.hidden_field :ancestry
  = f.hidden_field :parent_id
  fieldset.inputs
    ol
      li.string.input.required.stringish
        = f.label :title, "заголовок", class: "label"
        = f.text_field :title, placeholder: 'заголовок', required: true
      li.string.input.required.stringish
        = f.label :text, "основной текст", class: "label"
        = f.text_area :text, placeholder: 'текст, не обязательно', required: true, style: "height: 100px;"

  .panel
    h3 выбор файлов
    .panel_contents
      = f.fields_for [:attachments, @external_contact] do |a|
        ol
          li.string.input.required.stringish
            = a.label :attach, "файлы ", class: "label"
            = a.file_field :attach, name: "external_contact[attachments_attributes][][attach]", multiple: true
            = a.hidden_field :attacheable_type, value: @external_contact.class.name

  = f.submit

app/views/admin/external_contacts/_parent.html.slim
= link_to @external_contact.parent.title, [:admin, @external_contact.parent]

app/views/admin/external_contacts/_sub.html.slim
.index_as_table
  table id="index_table_external_contacts" class="index_table index" paginator="true" cellspacing="0" cellpadding="0" border="0"
    thead
      tr
        th class="col col-title" заголовок
        th class="col col-actions" функции

    tbody
      - @external_contact.children.each do |c|
        tr class="odd" id="external_contact_#{c.id}"
          td class="col col-title"
            = link_to c.title, [:admin, c], class: "view_link member_link"
          td class="col col-actions"
            .table_actions
              = link_to "открыть",       [:admin, c], class: "view_link member_link"
              = link_to "редактировать", edit_admin_external_contact_path(c), class: "edit_link member_link"
              = link_to "удалить",       admin_external_contact_path(c), class: "delete_link member_link", confirm: "Вы уверены, что хотите удалить это?", method: :delete

app/views/admin/external_contacts/_sub_functions.slim
= link_to "добавить подраздел", new_admin_external_contact_path(ancestry: @external_contact)

app/views/admin/external_contacts/_sub_item.html.slim
li
  = link_to mm.title, mm